// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAadqXzR51lZDVypBkKo81i-fRkdRL9rYA',
    appId: '1:613430880870:web:8f06fca34c0575c99b1ba7',
    messagingSenderId: '613430880870',
    projectId: 'return-to-firebase-8cbe4',
    authDomain: 'return-to-firebase-8cbe4.firebaseapp.com',
    storageBucket: 'return-to-firebase-8cbe4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVZEpuGieNumArNmM_YIdtbRoqDFjfkYg',
    appId: '1:613430880870:android:2a5a1247853b035e9b1ba7',
    messagingSenderId: '613430880870',
    projectId: 'return-to-firebase-8cbe4',
    storageBucket: 'return-to-firebase-8cbe4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQrR9RT4FmpIFgoBMNu9bXbJHh7OpUgaU',
    appId: '1:613430880870:ios:fb2e2af6701dfe4e9b1ba7',
    messagingSenderId: '613430880870',
    projectId: 'return-to-firebase-8cbe4',
    storageBucket: 'return-to-firebase-8cbe4.firebasestorage.app',
    iosBundleId: 'com.example.walkingGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQrR9RT4FmpIFgoBMNu9bXbJHh7OpUgaU',
    appId: '1:613430880870:ios:fb2e2af6701dfe4e9b1ba7',
    messagingSenderId: '613430880870',
    projectId: 'return-to-firebase-8cbe4',
    storageBucket: 'return-to-firebase-8cbe4.firebasestorage.app',
    iosBundleId: 'com.example.walkingGroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAadqXzR51lZDVypBkKo81i-fRkdRL9rYA',
    appId: '1:613430880870:web:4a47612070eb63e09b1ba7',
    messagingSenderId: '613430880870',
    projectId: 'return-to-firebase-8cbe4',
    authDomain: 'return-to-firebase-8cbe4.firebaseapp.com',
    storageBucket: 'return-to-firebase-8cbe4.firebasestorage.app',
  );

}